import 'package:dash_and_tag_web_site/Utils/All_Images/all_images.dart';
import 'package:dash_and_tag_web_site/Utils/All_Texts/HomePageText/home_page_text.dart';

import '../All_Texts/Quality_Assurance_PageText/quality_assurance_page_text.dart';

class AllListsManager {

  //Home Page Men, Women, Kids Sliders List
  static List womensClothList = [
    "assets/images/womens_cloth/1.png",
    "assets/images/womens_cloth/2.png",
    "assets/images/womens_cloth/3.jpg",
    "assets/images/womens_cloth/4.jpg",
    "assets/images/womens_cloth/5.jpg",
    "assets/images/womens_cloth/6.jpg",
  ];

  static List kidsClothList = [
    "assets/images/kids_cloth/1.jpg",
    "assets/images/kids_cloth/2.jpg",
    "assets/images/kids_cloth/3.jpg",
    "assets/images/kids_cloth/4.jpg",
    "assets/images/kids_cloth/5.jpg",
    "assets/images/kids_cloth/6.jpg",
    "assets/images/kids_cloth/7.jpg",
    "assets/images/kids_cloth/8.jpg",
    "assets/images/kids_cloth/9.jpg",
    "assets/images/kids_cloth/10.jpg",
    "assets/images/kids_cloth/11.jpg",
    "assets/images/kids_cloth/12.jpg",
    "assets/images/kids_cloth/13.jpg",
    "assets/images/kids_cloth/14.jpg",
    "assets/images/kids_cloth/15.jpg",
    "assets/images/kids_cloth/16.jpg",
    "assets/images/kids_cloth/17.jpg",
    "assets/images/kids_cloth/18.jpg",
    "assets/images/kids_cloth/19.jpg",
    "assets/images/kids_cloth/20.jpg",
    "assets/images/kids_cloth/21.jpg",
    "assets/images/kids_cloth/22.jpg",
    "assets/images/kids_cloth/23.jpg",
    "assets/images/kids_cloth/24.jpg",
    "assets/images/kids_cloth/25.jpg",
    "assets/images/kids_cloth/26.jpg",
    "assets/images/kids_cloth/27.jpg",

  ];

  static List mainSliderImageList = [
    "assets/images/main_slider_images/1.png",
    "assets/images/main_slider_images/2.png",
    "assets/images/main_slider_images/3.png",
    "assets/images/main_slider_images/4.png",
    "assets/images/main_slider_images/5.png",
    "assets/images/main_slider_images/6.png",
    "assets/images/main_slider_images/7.png",
    "assets/images/main_slider_images/8.png",
    "assets/images/main_slider_images/9.png",
    "assets/images/main_slider_images/10.png",
    "assets/images/main_slider_images/11.png",
    "assets/images/main_slider_images/12.png",
    "assets/images/main_slider_images/13.png",
  ];


  static List complientsList = [
    "assets/images/complaients/1.jpeg",
    "assets/images/complaients/2.png",
    "assets/images/complaients/3.png",
    "assets/images/complaients/4.png",
    "assets/images/complaients/5.png",
    "assets/images/complaients/6.png",
    "assets/images/complaients/7.webp",
    "assets/images/complaients/8.jpg",
  ];

  static List whyChooseUsList = [
    {
      "title": HomePageText.whyChooseUsQualityAndPriceControl,
      "description": HomePageText.whyChooseUsQualityAndPriceControlDescription,
    },
    {
      "title": HomePageText.whyChooseUsExperiencedTeam,
      "description": HomePageText.whyChooseUsExperiencedTeamDescription,
    },
    {
      "title": HomePageText.whyChooseUsComplianceAndCertification,
      "description":
          HomePageText.whyChooseUsComplianceAndCertificationDescription,
    },
    {
      "title": HomePageText.whyChooseUsAdvancedCADSystems,
      "description": HomePageText.whyChooseUsAdvancedCADSystemsDescription,
    },

    {
      "title": HomePageText.whyChooseUsExceptionalSamplingAndDesign,
      "description":
          HomePageText.whyChooseUsExceptionalSamplingAndDesignDescription,
    },

    {
      "title": HomePageText.whyChooseUsHighFashionAndIntricateValueAdditions,
      "description": HomePageText
          .whyChooseUsHighFashionAndIntricateValueAdditionsDescription,
    },
    {
      "title": HomePageText.whyChooseUsWideProductRange,
      "description": HomePageText.whyChooseUsWideProductRangeDescription,
    },
    {
      "title": HomePageText.whyChooseUsExpertiseHandworkAndBeadwork,
      "description":
          HomePageText.whyChooseUsExpertiseHandworkAndBeadworkDescription,
    },
    {
      "title": HomePageText.whyChooseUsComprehensiveInfrastructure,
      "description":
          HomePageText.whyChooseUsComprehensiveInfrastructureDescription,
    },
  ];

  //Products List

  //Accessories -> Clear
  static List accessoriesList = [
    "assets/images/products/Accessories/1.jpg",
    "assets/images/products/Accessories/2.jpg",
    "assets/images/products/Accessories/3.jpg",
    "assets/images/products/Accessories/4.jpg",
    "assets/images/products/Accessories/5.jpg",
    "assets/images/products/Accessories/6.jpg",
    "assets/images/products/Accessories/7.jpg",
    "assets/images/products/Accessories/8.jpg",
    "assets/images/products/Accessories/9.jpg",
    "assets/images/products/Accessories/10.jpg",
    "assets/images/products/Accessories/11.jpg",
    "assets/images/products/Accessories/12.jpg",
    "assets/images/products/Accessories/13.jpg",
    "assets/images/products/Accessories/14.jpg",
    "assets/images/products/Accessories/15.jpg",
    "assets/images/products/Accessories/16.jpg",
    "assets/images/products/Accessories/17.jpg",
    "assets/images/products/Accessories/18.jpg",
    "assets/images/products/Accessories/19.jpg",
    "assets/images/products/Accessories/20.jpg",
    "assets/images/products/Accessories/21.jpg",
    "assets/images/products/Accessories/22.jpg",
    "assets/images/products/Accessories/23.jpg",
    "assets/images/products/Accessories/24.jpg",
    "assets/images/products/Accessories/25.jpg",
    "assets/images/products/Accessories/26.jpg",
  ];

  //Boys Section -> Clear

  //Boys\Hoodies
  static List boysHoodiesList = [
    "assets/images/products/Boys/Hoodies/1.png",
    "assets/images/products/Boys/Hoodies/2.png",
    "assets/images/products/Boys/Hoodies/3.png",
    "assets/images/products/Boys/Hoodies/4.png",
    "assets/images/products/Boys/Hoodies/5.png",
    "assets/images/products/Boys/Hoodies/6.png",
    "assets/images/products/Boys/Hoodies/7.png",
    "assets/images/products/Boys/Hoodies/8.png",
    "assets/images/products/Boys/Hoodies/9.png",
    "assets/images/products/Boys/Hoodies/10.png",
    "assets/images/products/Boys/Hoodies/11.png",
    "assets/images/products/Boys/Hoodies/12.png",
    "assets/images/products/Boys/Hoodies/13.png",
    "assets/images/products/Boys/Hoodies/14.png",
    "assets/images/products/Boys/Hoodies/15.png",
    "assets/images/products/Boys/Hoodies/16.png",
    "assets/images/products/Boys/Hoodies/17.png",
    "assets/images/products/Boys/Hoodies/18.png",
    "assets/images/products/Boys/Hoodies/19.png",
    "assets/images/products/Boys/Hoodies/20.png",
    "assets/images/products/Boys/Hoodies/21.png",
    "assets/images/products/Boys/Hoodies/22.png",
    "assets/images/products/Boys/Hoodies/23.png",
    "assets/images/products/Boys/Hoodies/24.png",
    "assets/images/products/Boys/Hoodies/25.png",
    "assets/images/products/Boys/Hoodies/26.png",
    "assets/images/products/Boys/Hoodies/27.png",
    "assets/images/products/Boys/Hoodies/28.png",
    "assets/images/products/Boys/Hoodies/29.png",
    "assets/images/products/Boys/Hoodies/30.png",
    "assets/images/products/Boys/Hoodies/31.png",
    "assets/images/products/Boys/Hoodies/32.png",
    "assets/images/products/Boys/Hoodies/33.png",
  ];

  //Boys\Jens
  static List boysJensList = [
    "assets/images/products/Boys/Jens/3.png",
    "assets/images/products/Boys/Jens/4.png",
    "assets/images/products/Boys/Jens/5.png",
    "assets/images/products/Boys/Jens/6.png",
    "assets/images/products/Boys/Jens/7.png",
    "assets/images/products/Boys/Jens/8.png",
    "assets/images/products/Boys/Jens/9.png",
    "assets/images/products/Boys/Jens/10.png",
    "assets/images/products/Boys/Jens/11.png",
    "assets/images/products/Boys/Jens/12.png",
    "assets/images/products/Boys/Jens/13.png",
    "assets/images/products/Boys/Jens/14.png",
    "assets/images/products/Boys/Jens/15.png",
    "assets/images/products/Boys/Jens/16.png",
    "assets/images/products/Boys/Jens/17.png",
    "assets/images/products/Boys/Jens/18.png",
    "assets/images/products/Boys/Jens/19.png",
    "assets/images/products/Boys/Jens/20.png",
    "assets/images/products/Boys/Jens/21.png",
    "assets/images/products/Boys/Jens/22.png",
    "assets/images/products/Boys/Jens/23.png",
    "assets/images/products/Boys/Jens/24.png",
    "assets/images/products/Boys/Jens/25.png",
    "assets/images/products/Boys/Jens/26.png",
    "assets/images/products/Boys/Jens/27.png",
    "assets/images/products/Boys/Jens/28.png",
    "assets/images/products/Boys/Jens/29.png",
    "assets/images/products/Boys/Jens/30.png",
    "assets/images/products/Boys/Jens/31.png",
    "assets/images/products/Boys/Jens/32.png",
    "assets/images/products/Boys/Jens/33.png",
    "assets/images/products/Boys/Jens/34.png",
    "assets/images/products/Boys/Jens/35.png",
    "assets/images/products/Boys/Jens/36.png",
    "assets/images/products/Boys/Jens/37.png",
  ];

  //Boys\Polo Shirts
  static List boysPoloShirtList = [
    "assets/images/products/Boys/Polo Shirts/1.png",
    "assets/images/products/Boys/Polo Shirts/2.png",
    "assets/images/products/Boys/Polo Shirts/3.png",
    "assets/images/products/Boys/Polo Shirts/4.png",
    "assets/images/products/Boys/Polo Shirts/5.png",
    "assets/images/products/Boys/Polo Shirts/6.png",
    "assets/images/products/Boys/Polo Shirts/7.png",
    "assets/images/products/Boys/Polo Shirts/8.png",
    "assets/images/products/Boys/Polo Shirts/9.png",
    "assets/images/products/Boys/Polo Shirts/10.png",
    "assets/images/products/Boys/Polo Shirts/11.png",
    "assets/images/products/Boys/Polo Shirts/12.png",
    "assets/images/products/Boys/Polo Shirts/13.png",
    "assets/images/products/Boys/Polo Shirts/14.png",
    "assets/images/products/Boys/Polo Shirts/15.png",
    "assets/images/products/Boys/Polo Shirts/16.png",
    "assets/images/products/Boys/Polo Shirts/17.png",
    "assets/images/products/Boys/Polo Shirts/18.png",
    "assets/images/products/Boys/Polo Shirts/19.png",
    "assets/images/products/Boys/Polo Shirts/20.png",
    "assets/images/products/Boys/Polo Shirts/21.png",
    "assets/images/products/Boys/Polo Shirts/22.png",
    "assets/images/products/Boys/Polo Shirts/23.png",
    "assets/images/products/Boys/Polo Shirts/24.png",
    "assets/images/products/Boys/Polo Shirts/25.png",
    "assets/images/products/Boys/Polo Shirts/26.png",
  ];

  //Boys\shirt_and_pant
  static List boysShirtsAndPantsList = [
    "assets/images/products/Boys/shirt_and_pant/1.png",
    "assets/images/products/Boys/shirt_and_pant/2.png",
    "assets/images/products/Boys/shirt_and_pant/3.png",
    "assets/images/products/Boys/shirt_and_pant/4.png",
    "assets/images/products/Boys/shirt_and_pant/5.png",
    "assets/images/products/Boys/shirt_and_pant/6.png",
    "assets/images/products/Boys/shirt_and_pant/7.png",
    "assets/images/products/Boys/shirt_and_pant/8.png",
    "assets/images/products/Boys/shirt_and_pant/9.png",
    "assets/images/products/Boys/shirt_and_pant/10.png",
    "assets/images/products/Boys/shirt_and_pant/11.png",
    "assets/images/products/Boys/shirt_and_pant/12.png",
    "assets/images/products/Boys/shirt_and_pant/13.png",
    "assets/images/products/Boys/shirt_and_pant/14.png",
    "assets/images/products/Boys/shirt_and_pant/15.png",
    "assets/images/products/Boys/shirt_and_pant/16.png",
    "assets/images/products/Boys/shirt_and_pant/17.png",
    "assets/images/products/Boys/shirt_and_pant/18.png",
    "assets/images/products/Boys/shirt_and_pant/19.png",
    "assets/images/products/Boys/shirt_and_pant/20.png",
    "assets/images/products/Boys/shirt_and_pant/21.png",
    "assets/images/products/Boys/shirt_and_pant/22.png",
    "assets/images/products/Boys/shirt_and_pant/23.png",
    "assets/images/products/Boys/shirt_and_pant/24.png",
    "assets/images/products/Boys/shirt_and_pant/25.png",
    "assets/images/products/Boys/shirt_and_pant/26.png",
    "assets/images/products/Boys/shirt_and_pant/27.png",
    "assets/images/products/Boys/shirt_and_pant/28.png",
    "assets/images/products/Boys/shirt_and_pant/29.png",
    "assets/images/products/Boys/shirt_and_pant/30.png",
    "assets/images/products/Boys/shirt_and_pant/31.png",
    "assets/images/products/Boys/shirt_and_pant/32.png",
    "assets/images/products/Boys/shirt_and_pant/33.png",
    "assets/images/products/Boys/shirt_and_pant/34.png",
    "assets/images/products/Boys/shirt_and_pant/35.png",
    "assets/images/products/Boys/shirt_and_pant/36.png",
    "assets/images/products/Boys/shirt_and_pant/37.png",
    "assets/images/products/Boys/shirt_and_pant/38.png",
    "assets/images/products/Boys/shirt_and_pant/39.png",
    "assets/images/products/Boys/shirt_and_pant/40.png",
    "assets/images/products/Boys/shirt_and_pant/41.png",
    "assets/images/products/Boys/shirt_and_pant/42.png",
    "assets/images/products/Boys/shirt_and_pant/43.png",
    "assets/images/products/Boys/shirt_and_pant/44.png",
    "assets/images/products/Boys/shirt_and_pant/45.png",
    "assets/images/products/Boys/shirt_and_pant/46.png",
    "assets/images/products/Boys/shirt_and_pant/47.png",
    "assets/images/products/Boys/shirt_and_pant/48.png",
    "assets/images/products/Boys/shirt_and_pant/49.png",
    "assets/images/products/Boys/shirt_and_pant/50.png",
    "assets/images/products/Boys/shirt_and_pant/51.png",
    "assets/images/products/Boys/shirt_and_pant/52.png",
    "assets/images/products/Boys/shirt_and_pant/53.png",
    "assets/images/products/Boys/shirt_and_pant/54.png",
    "assets/images/products/Boys/shirt_and_pant/55.png",
    "assets/images/products/Boys/shirt_and_pant/56.png",
    "assets/images/products/Boys/shirt_and_pant/57.png",
    "assets/images/products/Boys/shirt_and_pant/58.png",
    "assets/images/products/Boys/shirt_and_pant/59.png",
    "assets/images/products/Boys/shirt_and_pant/60.png",
    "assets/images/products/Boys/shirt_and_pant/61.png",
    "assets/images/products/Boys/shirt_and_pant/62.png",
    "assets/images/products/Boys/shirt_and_pant/63.png",
    "assets/images/products/Boys/shirt_and_pant/64.png",
    "assets/images/products/Boys/shirt_and_pant/65.png",
    "assets/images/products/Boys/shirt_and_pant/66.png",
    "assets/images/products/Boys/shirt_and_pant/67.png",
    "assets/images/products/Boys/shirt_and_pant/68.png",
    "assets/images/products/Boys/shirt_and_pant/69.png",
    "assets/images/products/Boys/shirt_and_pant/70.png",
    "assets/images/products/Boys/shirt_and_pant/71.png",
    "assets/images/products/Boys/shirt_and_pant/72.png",
    "assets/images/products/Boys/shirt_and_pant/73.png",
    "assets/images/products/Boys/shirt_and_pant/74.png",
    "assets/images/products/Boys/shirt_and_pant/75.png",
  ];

  //Boys\short_and_cargo
  static List boysShortsAndCargoList = [
    "assets/images/products/Boys/short_and_cargo/1.png",
    "assets/images/products/Boys/short_and_cargo/2.png",
    "assets/images/products/Boys/short_and_cargo/3.png",
    "assets/images/products/Boys/short_and_cargo/4.png",
    "assets/images/products/Boys/short_and_cargo/5.png",
    "assets/images/products/Boys/short_and_cargo/6.png",
    "assets/images/products/Boys/short_and_cargo/7.png",
    "assets/images/products/Boys/short_and_cargo/8.png",
    "assets/images/products/Boys/short_and_cargo/9.png",
    "assets/images/products/Boys/short_and_cargo/10.png",
    "assets/images/products/Boys/short_and_cargo/11.png",
    "assets/images/products/Boys/short_and_cargo/12.png",
    "assets/images/products/Boys/short_and_cargo/13.png",
    "assets/images/products/Boys/short_and_cargo/14.png",
    "assets/images/products/Boys/short_and_cargo/15.png",
    "assets/images/products/Boys/short_and_cargo/16.png",
    "assets/images/products/Boys/short_and_cargo/17.png",
    "assets/images/products/Boys/short_and_cargo/18.png",
    "assets/images/products/Boys/short_and_cargo/19.png",
    "assets/images/products/Boys/short_and_cargo/20.png",
    "assets/images/products/Boys/short_and_cargo/21.png",
    "assets/images/products/Boys/short_and_cargo/22.png",
    "assets/images/products/Boys/short_and_cargo/23.png",
    "assets/images/products/Boys/short_and_cargo/24.png",
    "assets/images/products/Boys/short_and_cargo/25.png",
    "assets/images/products/Boys/short_and_cargo/26.png",
    "assets/images/products/Boys/short_and_cargo/27.png",
    "assets/images/products/Boys/short_and_cargo/28.png",
    "assets/images/products/Boys/short_and_cargo/29.png",
    "assets/images/products/Boys/short_and_cargo/30.png",
    "assets/images/products/Boys/short_and_cargo/31.png",
    "assets/images/products/Boys/short_and_cargo/32.png",
    "assets/images/products/Boys/short_and_cargo/33.png",
    "assets/images/products/Boys/short_and_cargo/34.png",
    "assets/images/products/Boys/short_and_cargo/35.png",
    "assets/images/products/Boys/short_and_cargo/36.png",
    "assets/images/products/Boys/short_and_cargo/37.png",
    "assets/images/products/Boys/short_and_cargo/38.png",
    "assets/images/products/Boys/short_and_cargo/39.png",
    "assets/images/products/Boys/short_and_cargo/40.png",
    "assets/images/products/Boys/short_and_cargo/41.png",
    "assets/images/products/Boys/short_and_cargo/42.png",
    "assets/images/products/Boys/short_and_cargo/43.png",
    "assets/images/products/Boys/short_and_cargo/44.png",
    "assets/images/products/Boys/short_and_cargo/45.png",
    "assets/images/products/Boys/short_and_cargo/46.png",
    "assets/images/products/Boys/short_and_cargo/47.png",
    "assets/images/products/Boys/short_and_cargo/48.png",
    "assets/images/products/Boys/short_and_cargo/49.png",
    "assets/images/products/Boys/short_and_cargo/50.png",
    "assets/images/products/Boys/short_and_cargo/51.png",
    "assets/images/products/Boys/short_and_cargo/52.png",
    "assets/images/products/Boys/short_and_cargo/53.png",
    "assets/images/products/Boys/short_and_cargo/54.png",
    "assets/images/products/Boys/short_and_cargo/55.png",
    "assets/images/products/Boys/short_and_cargo/56.png",
    "assets/images/products/Boys/short_and_cargo/57.png",
    "assets/images/products/Boys/short_and_cargo/58.png",
    "assets/images/products/Boys/short_and_cargo/59.png",
    "assets/images/products/Boys/short_and_cargo/60.png",
    "assets/images/products/Boys/short_and_cargo/61.png",
    "assets/images/products/Boys/short_and_cargo/62.png",
    "assets/images/products/Boys/short_and_cargo/63.png",
    "assets/images/products/Boys/short_and_cargo/64.png",
    "assets/images/products/Boys/short_and_cargo/65.png",
    "assets/images/products/Boys/short_and_cargo/66.png",
    "assets/images/products/Boys/short_and_cargo/67.png",
    "assets/images/products/Boys/short_and_cargo/68.png",
    "assets/images/products/Boys/short_and_cargo/69.png",
    "assets/images/products/Boys/short_and_cargo/70.png",
    "assets/images/products/Boys/short_and_cargo/71.png",
    "assets/images/products/Boys/short_and_cargo/72.png",
    "assets/images/products/Boys/short_and_cargo/73.png",
    "assets/images/products/Boys/short_and_cargo/74.png",
    "assets/images/products/Boys/short_and_cargo/75.png",
    "assets/images/products/Boys/short_and_cargo/76.png",
    "assets/images/products/Boys/short_and_cargo/77.png",
    "assets/images/products/Boys/short_and_cargo/78.png",
    "assets/images/products/Boys/short_and_cargo/79.png",
    "assets/images/products/Boys/short_and_cargo/80.png",
    "assets/images/products/Boys/short_and_cargo/81.png",
    "assets/images/products/Boys/short_and_cargo/82.png",
    "assets/images/products/Boys/short_and_cargo/83.png",
    "assets/images/products/Boys/short_and_cargo/84.png",


  ];

  //Boys\Sweaters
  static List boysSweatersList = [
    "assets/images/products/Boys/Sweaters/1.png",
    "assets/images/products/Boys/Sweaters/2.png",
    "assets/images/products/Boys/Sweaters/3.png",
    "assets/images/products/Boys/Sweaters/4.png",
    "assets/images/products/Boys/Sweaters/5.png",
    "assets/images/products/Boys/Sweaters/6.png",
    "assets/images/products/Boys/Sweaters/7.png",
    "assets/images/products/Boys/Sweaters/8.png",
    "assets/images/products/Boys/Sweaters/9.png",
    "assets/images/products/Boys/Sweaters/10.png",
    "assets/images/products/Boys/Sweaters/11.png",
    "assets/images/products/Boys/Sweaters/12.png",
    "assets/images/products/Boys/Sweaters/13.png",
    "assets/images/products/Boys/Sweaters/14.png",
    "assets/images/products/Boys/Sweaters/15.png",
    "assets/images/products/Boys/Sweaters/16.png",
    "assets/images/products/Boys/Sweaters/17.png",
    "assets/images/products/Boys/Sweaters/18.png",
    "assets/images/products/Boys/Sweaters/19.png",
    "assets/images/products/Boys/Sweaters/20.png",
    "assets/images/products/Boys/Sweaters/21.png",
    "assets/images/products/Boys/Sweaters/22.png",
    "assets/images/products/Boys/Sweaters/23.png",
    "assets/images/products/Boys/Sweaters/24.png",
    "assets/images/products/Boys/Sweaters/25.png",
    "assets/images/products/Boys/Sweaters/26.png",
    "assets/images/products/Boys/Sweaters/27.png",
    "assets/images/products/Boys/Sweaters/28.png",
    "assets/images/products/Boys/Sweaters/29.png",
    "assets/images/products/Boys/Sweaters/30.png",
    "assets/images/products/Boys/Sweaters/31.png",
    "assets/images/products/Boys/Sweaters/32.png",
    "assets/images/products/Boys/Sweaters/33.png",
    "assets/images/products/Boys/Sweaters/34.png",
    "assets/images/products/Boys/Sweaters/35.png",
    "assets/images/products/Boys/Sweaters/36.png",
    "assets/images/products/Boys/Sweaters/37.png",
    "assets/images/products/Boys/Sweaters/38.png",
    "assets/images/products/Boys/Sweaters/39.png",
    "assets/images/products/Boys/Sweaters/40.png",
    "assets/images/products/Boys/Sweaters/41.png",
    "assets/images/products/Boys/Sweaters/42.png",
    "assets/images/products/Boys/Sweaters/43.png",
    "assets/images/products/Boys/Sweaters/44.png",
    "assets/images/products/Boys/Sweaters/45.png",
    "assets/images/products/Boys/Sweaters/46.png",
    "assets/images/products/Boys/Sweaters/47.png",
    "assets/images/products/Boys/Sweaters/48.png",
    "assets/images/products/Boys/Sweaters/49.png",
    "assets/images/products/Boys/Sweaters/50.png",
    "assets/images/products/Boys/Sweaters/51.png",
    "assets/images/products/Boys/Sweaters/52.png",
    "assets/images/products/Boys/Sweaters/53.png",
    "assets/images/products/Boys/Sweaters/54.png",
    "assets/images/products/Boys/Sweaters/55.png",
    "assets/images/products/Boys/Sweaters/56.png",
    "assets/images/products/Boys/Sweaters/57.png",
    "assets/images/products/Boys/Sweaters/58.png",
    "assets/images/products/Boys/Sweaters/59.png",
    "assets/images/products/Boys/Sweaters/60.png",
    "assets/images/products/Boys/Sweaters/61.png",
    "assets/images/products/Boys/Sweaters/62.png",
    "assets/images/products/Boys/Sweaters/63.png",
    "assets/images/products/Boys/Sweaters/64.png",
    "assets/images/products/Boys/Sweaters/65.png",
    "assets/images/products/Boys/Sweaters/66.png",
    "assets/images/products/Boys/Sweaters/67.png",
    "assets/images/products/Boys/Sweaters/68.png",

  ];

  //Boys\T-Shirts
  static List boysTShirtsList = [
    "assets/images/products/Boys/T-Shirts/1.png",
    "assets/images/products/Boys/T-Shirts/2.png",
    "assets/images/products/Boys/T-Shirts/3.png",
    "assets/images/products/Boys/T-Shirts/4.png",
    "assets/images/products/Boys/T-Shirts/5.png",
    "assets/images/products/Boys/T-Shirts/6.png",
    "assets/images/products/Boys/T-Shirts/7.png",
    "assets/images/products/Boys/T-Shirts/8.png",
    "assets/images/products/Boys/T-Shirts/9.png",
    "assets/images/products/Boys/T-Shirts/10.png",
    "assets/images/products/Boys/T-Shirts/11.png",
    "assets/images/products/Boys/T-Shirts/12.png",
    "assets/images/products/Boys/T-Shirts/13.png",
    "assets/images/products/Boys/T-Shirts/14.png",
    "assets/images/products/Boys/T-Shirts/15.png",
    "assets/images/products/Boys/T-Shirts/16.png",
    "assets/images/products/Boys/T-Shirts/17.png",
    "assets/images/products/Boys/T-Shirts/18.png",
    "assets/images/products/Boys/T-Shirts/19.png",
    "assets/images/products/Boys/T-Shirts/20.png",
    "assets/images/products/Boys/T-Shirts/21.png",
    "assets/images/products/Boys/T-Shirts/22.png",
    "assets/images/products/Boys/T-Shirts/23.png",
    "assets/images/products/Boys/T-Shirts/24.png",
    "assets/images/products/Boys/T-Shirts/25.png",
    "assets/images/products/Boys/T-Shirts/26.png",
    "assets/images/products/Boys/T-Shirts/27.png",
    "assets/images/products/Boys/T-Shirts/28.png",
    "assets/images/products/Boys/T-Shirts/29.png",
    "assets/images/products/Boys/T-Shirts/30.png",
    "assets/images/products/Boys/T-Shirts/31.png",
    "assets/images/products/Boys/T-Shirts/32.png",
    "assets/images/products/Boys/T-Shirts/33.png",
    "assets/images/products/Boys/T-Shirts/34.png",
    "assets/images/products/Boys/T-Shirts/35.png",
    "assets/images/products/Boys/T-Shirts/36.png",
  ];





  //Girls Section -> Clear

  //Girls\Jens
  static List girlJensList = [
    "assets/images/products/Girls/Jens/1.jpg",
    "assets/images/products/Girls/Jens/2.png",
    "assets/images/products/Girls/Jens/3.png",
    "assets/images/products/Girls/Jens/4.png",
    "assets/images/products/Girls/Jens/5.png",
    "assets/images/products/Girls/Jens/6.png",
    "assets/images/products/Girls/Jens/7.png",
    "assets/images/products/Girls/Jens/8.png",
    "assets/images/products/Girls/Jens/9.png",
    "assets/images/products/Girls/Jens/10.png",
    "assets/images/products/Girls/Jens/11.png",
    "assets/images/products/Girls/Jens/12.png",
    "assets/images/products/Girls/Jens/13.png",
    "assets/images/products/Girls/Jens/14.png",
    "assets/images/products/Girls/Jens/15.png",
    "assets/images/products/Girls/Jens/16.png",
    "assets/images/products/Girls/Jens/17.png",
    "assets/images/products/Girls/Jens/18.png",
    "assets/images/products/Girls/Jens/19.png",
    "assets/images/products/Girls/Jens/20.png",
    "assets/images/products/Girls/Jens/21.png",
    "assets/images/products/Girls/Jens/22.png",
    "assets/images/products/Girls/Jens/23.png",
    "assets/images/products/Girls/Jens/24.png",
    "assets/images/products/Girls/Jens/25.png",
    "assets/images/products/Girls/Jens/26.png",
    "assets/images/products/Girls/Jens/27.png",
    "assets/images/products/Girls/Jens/28.png",
    "assets/images/products/Girls/Jens/29.png",
    "assets/images/products/Girls/Jens/30.png",
    "assets/images/products/Girls/Jens/31.png",
    "assets/images/products/Girls/Jens/32.png",
    "assets/images/products/Girls/Jens/33.png",
    "assets/images/products/Girls/Jens/34.png",
    "assets/images/products/Girls/Jens/35.png",
    "assets/images/products/Girls/Jens/36.png",
    "assets/images/products/Girls/Jens/37.png",
    "assets/images/products/Girls/Jens/38.png",
    "assets/images/products/Girls/Jens/39.png",
    "assets/images/products/Girls/Jens/40.png",
    "assets/images/products/Girls/Jens/41.png",
    "assets/images/products/Girls/Jens/42.png",
    "assets/images/products/Girls/Jens/43.png",
    "assets/images/products/Girls/Jens/44.png",
    "assets/images/products/Girls/Jens/45.png",
    "assets/images/products/Girls/Jens/46.jpg",
    "assets/images/products/Girls/Jens/47.jpg",
    "assets/images/products/Girls/Jens/48.jpg",
    "assets/images/products/Girls/Jens/49.png",
    "assets/images/products/Girls/Jens/50.png",
    "assets/images/products/Girls/Jens/51.png",
    "assets/images/products/Girls/Jens/52.png",
    "assets/images/products/Girls/Jens/53.png",
    "assets/images/products/Girls/Jens/54.png",
    "assets/images/products/Girls/Jens/55.png",
    "assets/images/products/Girls/Jens/56.png",
    "assets/images/products/Girls/Jens/57.png",
    "assets/images/products/Girls/Jens/58.png",
    "assets/images/products/Girls/Jens/59.jpg",
    "assets/images/products/Girls/Jens/60.png",
    "assets/images/products/Girls/Jens/61.png",
    "assets/images/products/Girls/Jens/62.jpg",
    "assets/images/products/Girls/Jens/63.jpg",
    "assets/images/products/Girls/Jens/64.jpg",

  ];

  //Girls\T-Shirts
  static List girlsTshirtsList = [
    "assets/images/products/Girls/T-Shirts/1.png",
    "assets/images/products/Girls/T-Shirts/2.png",
    "assets/images/products/Girls/T-Shirts/3.png",
    "assets/images/products/Girls/T-Shirts/4.png",
    "assets/images/products/Girls/T-Shirts/5.png",
    "assets/images/products/Girls/T-Shirts/6.png",
    "assets/images/products/Girls/T-Shirts/7.png",
    "assets/images/products/Girls/T-Shirts/8.png",
    "assets/images/products/Girls/T-Shirts/9.png",
    "assets/images/products/Girls/T-Shirts/10.png",
    "assets/images/products/Girls/T-Shirts/11.png",
    "assets/images/products/Girls/T-Shirts/12.png",
    "assets/images/products/Girls/T-Shirts/13.png",
    "assets/images/products/Girls/T-Shirts/14.png",
    "assets/images/products/Girls/T-Shirts/15.png",
    "assets/images/products/Girls/T-Shirts/16.png",
    "assets/images/products/Girls/T-Shirts/17.png",
    "assets/images/products/Girls/T-Shirts/18.png",
    "assets/images/products/Girls/T-Shirts/19.png",
    "assets/images/products/Girls/T-Shirts/20.png",
    "assets/images/products/Girls/T-Shirts/21.png",
    "assets/images/products/Girls/T-Shirts/22.png",
    "assets/images/products/Girls/T-Shirts/23.png",
    "assets/images/products/Girls/T-Shirts/24.png",
    "assets/images/products/Girls/T-Shirts/25.png",
    "assets/images/products/Girls/T-Shirts/26.png",
    "assets/images/products/Girls/T-Shirts/27.png",
    "assets/images/products/Girls/T-Shirts/28.png",
    "assets/images/products/Girls/T-Shirts/29.png",
    "assets/images/products/Girls/T-Shirts/30.png",
    "assets/images/products/Girls/T-Shirts/31.png",
    "assets/images/products/Girls/T-Shirts/32.png",
    "assets/images/products/Girls/T-Shirts/33.png",
    "assets/images/products/Girls/T-Shirts/34.png",
    "assets/images/products/Girls/T-Shirts/35.png",
    "assets/images/products/Girls/T-Shirts/36.png",
    "assets/images/products/Girls/T-Shirts/37.png",
    "assets/images/products/Girls/T-Shirts/38.png",
    "assets/images/products/Girls/T-Shirts/39.png",
    "assets/images/products/Girls/T-Shirts/40.png",
    "assets/images/products/Girls/T-Shirts/41.png",
    "assets/images/products/Girls/T-Shirts/42.png",
    "assets/images/products/Girls/T-Shirts/43.png",
    "assets/images/products/Girls/T-Shirts/44.png",
    "assets/images/products/Girls/T-Shirts/45.png",
    "assets/images/products/Girls/T-Shirts/46.png",
    "assets/images/products/Girls/T-Shirts/47.png",
    "assets/images/products/Girls/T-Shirts/48.png",
    "assets/images/products/Girls/T-Shirts/49.png",
    "assets/images/products/Girls/T-Shirts/50.png",
    "assets/images/products/Girls/T-Shirts/51.png",
    "assets/images/products/Girls/T-Shirts/52.png",
    "assets/images/products/Girls/T-Shirts/53.png",
    "assets/images/products/Girls/T-Shirts/54.png",
    "assets/images/products/Girls/T-Shirts/55.png",
    "assets/images/products/Girls/T-Shirts/56.png",
    "assets/images/products/Girls/T-Shirts/57.png",
    "assets/images/products/Girls/T-Shirts/58.png",
    "assets/images/products/Girls/T-Shirts/59.png",
    "assets/images/products/Girls/T-Shirts/60.png",
    "assets/images/products/Girls/T-Shirts/61.png",
    "assets/images/products/Girls/T-Shirts/62.png",

  ];

  //Polo Shirts
  static List girlsPoloShirtsList = [
    "assets/images/products/Girls/Polo Shirts/1.png",
    "assets/images/products/Girls/Polo Shirts/2.png",
    "assets/images/products/Girls/Polo Shirts/3.png",
    "assets/images/products/Girls/Polo Shirts/4.png",
    "assets/images/products/Girls/Polo Shirts/5.png",
    "assets/images/products/Girls/Polo Shirts/6.png",
    "assets/images/products/Girls/Polo Shirts/7.png",
    "assets/images/products/Girls/Polo Shirts/8.png",
    "assets/images/products/Girls/Polo Shirts/9.png",
    "assets/images/products/Girls/Polo Shirts/10.png",
    "assets/images/products/Girls/Polo Shirts/11.png",
    "assets/images/products/Girls/Polo Shirts/12.png",
    "assets/images/products/Girls/Polo Shirts/13.png",
    "assets/images/products/Girls/Polo Shirts/14.png",
    "assets/images/products/Girls/Polo Shirts/15.png",
    "assets/images/products/Girls/Polo Shirts/16.png",
    "assets/images/products/Girls/Polo Shirts/17.png",
    "assets/images/products/Girls/Polo Shirts/18.png",
    "assets/images/products/Girls/Polo Shirts/19.png",
    "assets/images/products/Girls/Polo Shirts/20.png",
    "assets/images/products/Girls/Polo Shirts/21.png",
    "assets/images/products/Girls/Polo Shirts/22.png",
    "assets/images/products/Girls/Polo Shirts/23.png",
    "assets/images/products/Girls/Polo Shirts/24.png",
    "assets/images/products/Girls/Polo Shirts/25.png",
    "assets/images/products/Girls/Polo Shirts/26.png",
    "assets/images/products/Girls/Polo Shirts/27.png",
    "assets/images/products/Girls/Polo Shirts/28.png",
    "assets/images/products/Girls/Polo Shirts/29.png",
    "assets/images/products/Girls/Polo Shirts/30.png",
    "assets/images/products/Girls/Polo Shirts/31.png",
    "assets/images/products/Girls/Polo Shirts/32.png",
    "assets/images/products/Girls/Polo Shirts/33.png",
    "assets/images/products/Girls/Polo Shirts/34.png",
    "assets/images/products/Girls/Polo Shirts/35.png",
    "assets/images/products/Girls/Polo Shirts/36.png",
    "assets/images/products/Girls/Polo Shirts/37.png",
    "assets/images/products/Girls/Polo Shirts/38.png",
    "assets/images/products/Girls/Polo Shirts/39.png",
    "assets/images/products/Girls/Polo Shirts/40.png",
    "assets/images/products/Girls/Polo Shirts/41.png",
    "assets/images/products/Girls/Polo Shirts/42.png",
    "assets/images/products/Girls/Polo Shirts/43.png",
    "assets/images/products/Girls/Polo Shirts/44.png",
    "assets/images/products/Girls/Polo Shirts/45.png",
    "assets/images/products/Girls/Polo Shirts/46.png",
    "assets/images/products/Girls/Polo Shirts/47.png",
    "assets/images/products/Girls/Polo Shirts/48.png",
    "assets/images/products/Girls/Polo Shirts/49.png",
    "assets/images/products/Girls/Polo Shirts/50.png",
    "assets/images/products/Girls/Polo Shirts/51.png",
    "assets/images/products/Girls/Polo Shirts/52.png",
    "assets/images/products/Girls/Polo Shirts/53.png",
    "assets/images/products/Girls/Polo Shirts/54.png",
    "assets/images/products/Girls/Polo Shirts/55.png",
    "assets/images/products/Girls/Polo Shirts/56.png",
    "assets/images/products/Girls/Polo Shirts/57.png",
    "assets/images/products/Girls/Polo Shirts/58.png",
    "assets/images/products/Girls/Polo Shirts/59.png",
    "assets/images/products/Girls/Polo Shirts/60.png",

  ];

  //Girls\shirt_and_pant
  static List girlsShirtsAndPantsList = [
    "assets/images/products/Girls/shirt_and_pant/1.jpg",
    "assets/images/products/Girls/shirt_and_pant/2.png",
    "assets/images/products/Girls/shirt_and_pant/3.png",
    "assets/images/products/Girls/shirt_and_pant/4.png",
    "assets/images/products/Girls/shirt_and_pant/5.png",
    "assets/images/products/Girls/shirt_and_pant/6.png",
    "assets/images/products/Girls/shirt_and_pant/7.png",
    "assets/images/products/Girls/shirt_and_pant/8.png",
    "assets/images/products/Girls/shirt_and_pant/9.png",
    "assets/images/products/Girls/shirt_and_pant/10.png",
    "assets/images/products/Girls/shirt_and_pant/11.png",
    "assets/images/products/Girls/shirt_and_pant/12.png",
    "assets/images/products/Girls/shirt_and_pant/13.jpg",
    "assets/images/products/Girls/shirt_and_pant/14.jpg",
    "assets/images/products/Girls/shirt_and_pant/15.jpg",
    "assets/images/products/Girls/shirt_and_pant/16.jpg",
    "assets/images/products/Girls/shirt_and_pant/17.jpg",
    "assets/images/products/Girls/shirt_and_pant/18.jpg",
    "assets/images/products/Girls/shirt_and_pant/19.png",
    "assets/images/products/Girls/shirt_and_pant/20.png",
    "assets/images/products/Girls/shirt_and_pant/21.png",
    "assets/images/products/Girls/shirt_and_pant/22.png",
    "assets/images/products/Girls/shirt_and_pant/23.png",
    "assets/images/products/Girls/shirt_and_pant/24.jpg",
    "assets/images/products/Girls/shirt_and_pant/25.jpg",
    "assets/images/products/Girls/shirt_and_pant/26.jpg",
    "assets/images/products/Girls/shirt_and_pant/27.png",
    "assets/images/products/Girls/shirt_and_pant/28.jpg",
    "assets/images/products/Girls/shirt_and_pant/30.jpg",
    "assets/images/products/Girls/shirt_and_pant/33.jpg",
    "assets/images/products/Girls/shirt_and_pant/34.jpg",
    "assets/images/products/Girls/shirt_and_pant/35.jpg",
    "assets/images/products/Girls/shirt_and_pant/37.jpg",
    "assets/images/products/Girls/shirt_and_pant/38.jpg",
    "assets/images/products/Girls/shirt_and_pant/39.jpg",
    "assets/images/products/Girls/shirt_and_pant/40.jpg",
    "assets/images/products/Girls/shirt_and_pant/41.jpg",
    "assets/images/products/Girls/shirt_and_pant/42.jpg",
  ];

  //Girls\Hoodies
  static List girlsHoodiesList = [
    "assets/images/products/Girls/Hoodies/1.jpg",
    "assets/images/products/Girls/Hoodies/2.jpg",
    "assets/images/products/Girls/Hoodies/3.jpg",
    "assets/images/products/Girls/Hoodies/4.jpg",
    "assets/images/products/Girls/Hoodies/5.png",
    "assets/images/products/Girls/Hoodies/6.png",
    "assets/images/products/Girls/Hoodies/7.png",
    "assets/images/products/Girls/Hoodies/8.png",
    "assets/images/products/Girls/Hoodies/9.png",
    "assets/images/products/Girls/Hoodies/10.png",
  ];

  //Girls\short_and_cargo
  static List girlsShortsAndCargoList = [
    "assets/images/products/Girls/short_and_cargo/1.jpg",
    "assets/images/products/Girls/short_and_cargo/2.jpg",
    "assets/images/products/Girls/short_and_cargo/3.jpg",
    "assets/images/products/Girls/short_and_cargo/4.jpg",
    "assets/images/products/Girls/short_and_cargo/5.jpg",
    "assets/images/products/Girls/short_and_cargo/6.jpg",
    "assets/images/products/Girls/short_and_cargo/7.jpg",
    "assets/images/products/Girls/short_and_cargo/8.png",
  ];

  //Girls\Sweaters
  static List girlsSweatersList = [
    "assets/images/products/Girls/Sweaters/1.jpg",
    "assets/images/products/Girls/Sweaters/2.jpg",
    "assets/images/products/Girls/Sweaters/3.png",
    "assets/images/products/Girls/Sweaters/4.png",
    "assets/images/products/Girls/Sweaters/5.png",
    "assets/images/products/Girls/Sweaters/6.png",
    "assets/images/products/Girls/Sweaters/7.png",
    "assets/images/products/Girls/Sweaters/8.png",
    "assets/images/products/Girls/Sweaters/9.jpg",
    "assets/images/products/Girls/Sweaters/10.jpg"
  ];

  //Juit Product Section ->
  static List justProductList = [];

  //Leather Product List -> Clear
  static List leatherProductList = [
    "assets/images/products/leather_products/1.jpg",
    "assets/images/products/leather_products/2.jpg",
    "assets/images/products/leather_products/3.jpg",
    "assets/images/products/leather_products/4.jpg",
    "assets/images/products/leather_products/5.jpg",
    "assets/images/products/leather_products/6.jpg",
    "assets/images/products/leather_products/7.jpg",
    "assets/images/products/leather_products/8.jpg",
    "assets/images/products/leather_products/9.jpg",
    "assets/images/products/leather_products/10.jpg",
    "assets/images/products/leather_products/11.jpg",
    "assets/images/products/leather_products/12.jpg",
    "assets/images/products/leather_products/13.jpg",
    "assets/images/products/leather_products/14.jpg",
    "assets/images/products/leather_products/15.jpg",
    "assets/images/products/leather_products/16.jpg",
    "assets/images/products/leather_products/17.jpg",
    "assets/images/products/leather_products/18.jpg",
    "assets/images/products/leather_products/19.jpg",
    "assets/images/products/leather_products/20.jpg",
    "assets/images/products/leather_products/21.jpg",
    "assets/images/products/leather_products/22.jpg",
    "assets/images/products/leather_products/23.jpg",
    "assets/images/products/leather_products/24.jpg",
    "assets/images/products/leather_products/25.jpg",
    "assets/images/products/leather_products/26.jpg",
    "assets/images/products/leather_products/27.jpg",
    "assets/images/products/leather_products/28.jpg",
    "assets/images/products/leather_products/29.jpg",
    "assets/images/products/leather_products/30.jpg",
    "assets/images/products/leather_products/31.jpg",
    "assets/images/products/leather_products/32.jpg",
    "assets/images/products/leather_products/33.jpg",
    "assets/images/products/leather_products/34.jpg",
    "assets/images/products/leather_products/35.jpg",
    "assets/images/products/leather_products/36.jpg",
    "assets/images/products/leather_products/37.jpg",
    "assets/images/products/leather_products/38.jpg",
    "assets/images/products/leather_products/39.jpg",
    "assets/images/products/leather_products/40.jpg",
    "assets/images/products/leather_products/41.jpg",
    "assets/images/products/leather_products/42.jpg",
    "assets/images/products/leather_products/43.jpg",
    "assets/images/products/leather_products/44.jpg",
    "assets/images/products/leather_products/45.jpg",
    "assets/images/products/leather_products/46.jpg",
  ];







  //Mens Section -> Clear

  //MensJeansList
  static List mensJeansList = [
    "assets/images/products/men/jens/18.png",
    "assets/images/products/men/jens/19.png",
    "assets/images/products/men/jens/20.png",
    "assets/images/products/men/jens/21.png",
    "assets/images/products/men/jens/22.png",
    "assets/images/products/men/jens/23.png",
    "assets/images/products/men/jens/24.png",
    "assets/images/products/men/jens/25.png",
    "assets/images/products/men/jens/26.png",
    "assets/images/products/men/jens/27.png",
    "assets/images/products/men/jens/28.png",
    "assets/images/products/men/jens/29.png",
    "assets/images/products/men/jens/30.png",
    "assets/images/products/men/jens/31.png",
    "assets/images/products/men/jens/32.png",
    "assets/images/products/men/jens/33.png",
  ];

  //Mens T-Shirts List
  static List mensTShirtsList = [
    "assets/images/products/men/T-Shirts/1.png",
    "assets/images/products/men/T-Shirts/2.png",
    "assets/images/products/men/T-Shirts/3.png",
    "assets/images/products/men/T-Shirts/4.png",
    "assets/images/products/men/T-Shirts/5.png",
    "assets/images/products/men/T-Shirts/6.png",
    "assets/images/products/men/T-Shirts/7.png",
    "assets/images/products/men/T-Shirts/8.png",
    "assets/images/products/men/T-Shirts/9.png",
    "assets/images/products/men/T-Shirts/10.png",
    "assets/images/products/men/T-Shirts/11.png",
    "assets/images/products/men/T-Shirts/12.png",
    "assets/images/products/men/T-Shirts/13.png",
    "assets/images/products/men/T-Shirts/14.png",
    "assets/images/products/men/T-Shirts/15.png",
    "assets/images/products/men/T-Shirts/16.png",
    "assets/images/products/men/T-Shirts/17.png",
    "assets/images/products/men/T-Shirts/18.png",
    "assets/images/products/men/T-Shirts/19.png",
    "assets/images/products/men/T-Shirts/20.png",
    "assets/images/products/men/T-Shirts/22.png",
    "assets/images/products/men/T-Shirts/23.png",
    "assets/images/products/men/T-Shirts/24.png",
    "assets/images/products/men/T-Shirts/25.png",
    "assets/images/products/men/T-Shirts/26.png",
    "assets/images/products/men/T-Shirts/27.png",
    "assets/images/products/men/T-Shirts/28.png",
    "assets/images/products/men/T-Shirts/29.png",
    "assets/images/products/men/T-Shirts/30.png",
    "assets/images/products/men/T-Shirts/31.png",
    "assets/images/products/men/T-Shirts/32.png",
    "assets/images/products/men/T-Shirts/33.png",
    "assets/images/products/men/T-Shirts/34.png",
  ];

  //men\Hoodies
  static List mensHoodiesList = [
    "assets/images/products/men/Hoodies/1.jpg",
    "assets/images/products/men/Hoodies/2.png",
    "assets/images/products/men/Hoodies/3.png",
    "assets/images/products/men/Hoodies/4.jpg",
    "assets/images/products/men/Hoodies/5.jpg",
    "assets/images/products/men/Hoodies/6.jpg",
    "assets/images/products/men/Hoodies/7.jpg",
    "assets/images/products/men/Hoodies/8.jpg",
    "assets/images/products/men/Hoodies/9.png",
    "assets/images/products/men/Hoodies/10.png",
  ];

  //men\Jackets
  static List mensJacketsList = [
    "assets/images/products/men/Jackets/1.png",
    "assets/images/products/men/Jackets/2.png",
    "assets/images/products/men/Jackets/3.png",
    "assets/images/products/men/Jackets/4.png",
    "assets/images/products/men/Jackets/5.png",
    "assets/images/products/men/Jackets/6.png",
    "assets/images/products/men/Jackets/7.png",
    "assets/images/products/men/Jackets/8.png",
    "assets/images/products/men/Jackets/9.png",
    "assets/images/products/men/Jackets/12.png",
    "assets/images/products/men/Jackets/13.jpg",
    "assets/images/products/men/Jackets/14.jpg",
    "assets/images/products/men/Jackets/15.jpg",
    "assets/images/products/men/Jackets/16.jpg",
    "assets/images/products/men/Jackets/17.jpg",
    "assets/images/products/men/Jackets/18.png",
    "assets/images/products/men/Jackets/19.png",
    "assets/images/products/men/Jackets/20.png",
    "assets/images/products/men/Jackets/21.jpg",
  ];

  //MenPolo List
  static List mensPoloShirts = [
    "assets/images/products/men/Polo Shirts/1.png",
    "assets/images/products/men/Polo Shirts/2.png",
    "assets/images/products/men/Polo Shirts/3.png",
    "assets/images/products/men/Polo Shirts/4.png",
    "assets/images/products/men/Polo Shirts/5.png",
    "assets/images/products/men/Polo Shirts/6.jpg",
    "assets/images/products/men/Polo Shirts/7.png",
    "assets/images/products/men/Polo Shirts/8.png",
    "assets/images/products/men/Polo Shirts/9.png",
    "assets/images/products/men/Polo Shirts/10.png",
    "assets/images/products/men/Polo Shirts/11.png",
    "assets/images/products/men/Polo Shirts/12.png",
    "assets/images/products/men/Polo Shirts/13.png",
    "assets/images/products/men/Polo Shirts/14.png",
    "assets/images/products/men/Polo Shirts/15.png",
    "assets/images/products/men/Polo Shirts/16.png",
    "assets/images/products/men/Polo Shirts/17.png",

  ];

  //Men shirt_and_pant List
  static List menShirtsAndPantsList = [
    "assets/images/products/men/shirt_and_pant/3.png",
    "assets/images/products/men/shirt_and_pant/5.png",
    "assets/images/products/men/shirt_and_pant/6.png",
    "assets/images/products/men/shirt_and_pant/7.png",
    "assets/images/products/men/shirt_and_pant/8.png",
    "assets/images/products/men/shirt_and_pant/9.png",
    "assets/images/products/men/shirt_and_pant/10.png",
    "assets/images/products/men/shirt_and_pant/11.png",
    "assets/images/products/men/shirt_and_pant/12.png",
    "assets/images/products/men/shirt_and_pant/13.png",
    "assets/images/products/men/shirt_and_pant/14.png",
    "assets/images/products/men/shirt_and_pant/15.png",
    "assets/images/products/men/shirt_and_pant/16.png",
    "assets/images/products/men/shirt_and_pant/17.png",
    "assets/images/products/men/shirt_and_pant/18.png",
    "assets/images/products/men/shirt_and_pant/19.png",
    "assets/images/products/men/shirt_and_pant/20.png",
    "assets/images/products/men/shirt_and_pant/21.png",
    "assets/images/products/men/shirt_and_pant/22.png",
    "assets/images/products/men/shirt_and_pant/23.png",
    "assets/images/products/men/shirt_and_pant/24.png",
    "assets/images/products/men/shirt_and_pant/25.png",
    "assets/images/products/men/shirt_and_pant/26.png",
    "assets/images/products/men/shirt_and_pant/27.png",
    "assets/images/products/men/shirt_and_pant/28.png",
    "assets/images/products/men/shirt_and_pant/29.png",
    "assets/images/products/men/shirt_and_pant/30.png",
    "assets/images/products/men/shirt_and_pant/31.png",
    "assets/images/products/men/shirt_and_pant/32.png",
    "assets/images/products/men/shirt_and_pant/33.png",
    "assets/images/products/men/shirt_and_pant/34.png",
    "assets/images/products/men/shirt_and_pant/35.png",
    "assets/images/products/men/shirt_and_pant/36.png",
    "assets/images/products/men/shirt_and_pant/37.png",
  ];

  //Mens Shorts And Cargo List
  static List mensShortsAndCargoList = [
    "assets/images/products/men/short_and_cargo/1.jpg",
    "assets/images/products/men/short_and_cargo/2.jpg",
    "assets/images/products/men/short_and_cargo/3.jpg",
    "assets/images/products/men/short_and_cargo/4.png",
    "assets/images/products/men/short_and_cargo/5.png",
    "assets/images/products/men/short_and_cargo/6.png",
    "assets/images/products/men/short_and_cargo/7.png",
    "assets/images/products/men/short_and_cargo/8.png",
    "assets/images/products/men/short_and_cargo/9.png",
    "assets/images/products/men/short_and_cargo/10.png",
    "assets/images/products/men/short_and_cargo/11.jpg",
    "assets/images/products/men/short_and_cargo/12.jpg",
    "assets/images/products/men/short_and_cargo/13.jpg",
    "assets/images/products/men/short_and_cargo/14.jpg",
    "assets/images/products/men/short_and_cargo/15.jpg",
    "assets/images/products/men/short_and_cargo/16.jpg",
    "assets/images/products/men/short_and_cargo/17.jpg",
    "assets/images/products/men/short_and_cargo/18.png",
    "assets/images/products/men/short_and_cargo/19.png",
    "assets/images/products/men/short_and_cargo/20.png",
    "assets/images/products/men/short_and_cargo/21.png",
    "assets/images/products/men/short_and_cargo/22.png",
    "assets/images/products/men/short_and_cargo/23.png",
    "assets/images/products/men/short_and_cargo/24.png",
    "assets/images/products/men/short_and_cargo/25.png",
    "assets/images/products/men/short_and_cargo/26.png",
    "assets/images/products/men/short_and_cargo/27.png",
    "assets/images/products/men/short_and_cargo/28.png",
    "assets/images/products/men/short_and_cargo/29.png",
    "assets/images/products/men/short_and_cargo/30.png",
    "assets/images/products/men/short_and_cargo/31.png",
    "assets/images/products/men/short_and_cargo/32.png",
    "assets/images/products/men/short_and_cargo/33.png",
    "assets/images/products/men/short_and_cargo/34.png",
    "assets/images/products/men/short_and_cargo/35.png",

  ];

  //Mens Sweaters List
  static List mensSweatersList = [
    "assets/images/products/men/Sweaters/1.png",
    "assets/images/products/men/Sweaters/2.png",
    "assets/images/products/men/Sweaters/3.png",
    "assets/images/products/men/Sweaters/4.png",
    "assets/images/products/men/Sweaters/5.png",
    "assets/images/products/men/Sweaters/6.png",
    "assets/images/products/men/Sweaters/7.png",
    "assets/images/products/men/Sweaters/8.png",
    "assets/images/products/men/Sweaters/9.png",
    "assets/images/products/men/Sweaters/10.png",
    "assets/images/products/men/Sweaters/11.png",
    "assets/images/products/men/Sweaters/12.png",
    "assets/images/products/men/Sweaters/13.png",
    "assets/images/products/men/Sweaters/14.png",
    "assets/images/products/men/Sweaters/15.png",
    "assets/images/products/men/Sweaters/16.jpg",
    "assets/images/products/men/Sweaters/17.png",
    "assets/images/products/men/Sweaters/18.jpg",
    "assets/images/products/men/Sweaters/19.jpg",
    "assets/images/products/men/Sweaters/20.jpg",
    "assets/images/products/men/Sweaters/21.jpg",
    "assets/images/products/men/Sweaters/22.jpg",
    "assets/images/products/men/Sweaters/23.jpg",
    "assets/images/products/men/Sweaters/24.jpg",
    "assets/images/products/men/Sweaters/25.jpg",
    "assets/images/products/men/Sweaters/26.jpg",
    "assets/images/products/men/Sweaters/27.jpg",
    "assets/images/products/men/Sweaters/28.jpg",
    "assets/images/products/men/Sweaters/29.jpg",
    "assets/images/products/men/Sweaters/30.jpg",
    "assets/images/products/men/Sweaters/31.jpg",
    "assets/images/products/men/Sweaters/32.jpg",
    "assets/images/products/men/Sweaters/33.jpg",
    "assets/images/products/men/Sweaters/34.jpg",
    "assets/images/products/men/Sweaters/35.jpg",
    "assets/images/products/men/Sweaters/36.jpg",
    "assets/images/products/men/Sweaters/37.png",
    "assets/images/products/men/Sweaters/38.png",
    "assets/images/products/men/Sweaters/39.png",
    "assets/images/products/men/Sweaters/40.png",
    "assets/images/products/men/Sweaters/41.png",
    "assets/images/products/men/Sweaters/42.png",
    "assets/images/products/men/Sweaters/43.png",
    "assets/images/products/men/Sweaters/44.png",
    "assets/images/products/men/Sweaters/45.png",
    "assets/images/products/men/Sweaters/46.png",
    "assets/images/products/men/Sweaters/47.png",
    "assets/images/products/men/Sweaters/48.png",
    "assets/images/products/men/Sweaters/49.png",
    "assets/images/products/men/Sweaters/50.png",
    "assets/images/products/men/Sweaters/51.png",
    "assets/images/products/men/Sweaters/52.png",
    "assets/images/products/men/Sweaters/53.png",
    "assets/images/products/men/Sweaters/54.png",
    "assets/images/products/men/Sweaters/55.png",
    "assets/images/products/men/Sweaters/56.png",
    "assets/images/products/men/Sweaters/57.png",
  ];







  //Womens Section -> clear
  //Womens HoodiesSection
  static List womenHoodiesList = [
    "assets/images/products/Women/Hoodies/1.png",
    "assets/images/products/Women/Hoodies/2.jpg",
    "assets/images/products/Women/Hoodies/3.jpg",
    "assets/images/products/Women/Hoodies/4.jpg",
    "assets/images/products/Women/Hoodies/5.png",
    "assets/images/products/Women/Hoodies/6.png",
    "assets/images/products/Women/Hoodies/7.png",
    "assets/images/products/Women/Hoodies/8.png",
    "assets/images/products/Women/Hoodies/9.png",
    "assets/images/products/Women/Hoodies/10.png",
    "assets/images/products/Women/Hoodies/11.png",
    "assets/images/products/Women/Hoodies/12.png",
    "assets/images/products/Women/Hoodies/13.png",
    "assets/images/products/Women/Hoodies/14.png",
    "assets/images/products/Women/Hoodies/15.png",
    "assets/images/products/Women/Hoodies/16.png",
    "assets/images/products/Women/Hoodies/17.png",
    "assets/images/products/Women/Hoodies/18.png",
    "assets/images/products/Women/Hoodies/19.png",
    "assets/images/products/Women/Hoodies/20.png",
    "assets/images/products/Women/Hoodies/21.png",
    "assets/images/products/Women/Hoodies/22.png",
    "assets/images/products/Women/Hoodies/23.png",
    "assets/images/products/Women/Hoodies/24.png",
    "assets/images/products/Women/Hoodies/25.png",
    "assets/images/products/Women/Hoodies/26.png",
    "assets/images/products/Women/Hoodies/27.png",
    "assets/images/products/Women/Hoodies/28.png",
    "assets/images/products/Women/Hoodies/29.png",
    "assets/images/products/Women/Hoodies/30.png",
    "assets/images/products/Women/Hoodies/31.png",
    "assets/images/products/Women/Hoodies/32.png",
    "assets/images/products/Women/Hoodies/33.png",
    "assets/images/products/Women/Hoodies/34.png",
    "assets/images/products/Women/Hoodies/35.png",
    "assets/images/products/Women/Hoodies/36.png",
    "assets/images/products/Women/Hoodies/37.png",
    "assets/images/products/Women/Hoodies/38.png",
    "assets/images/products/Women/Hoodies/39.png",
    "assets/images/products/Women/Hoodies/40.png",
    "assets/images/products/Women/Hoodies/41.png",
    "assets/images/products/Women/Hoodies/42.png",
    "assets/images/products/Women/Hoodies/43.png",
    "assets/images/products/Women/Hoodies/44.png",
    "assets/images/products/Women/Hoodies/45.png",
    "assets/images/products/Women/Hoodies/46.png",
    "assets/images/products/Women/Hoodies/47.png",
    "assets/images/products/Women/Hoodies/48.png",
    "assets/images/products/Women/Hoodies/49.png",
    "assets/images/products/Women/Hoodies/50.png",
    "assets/images/products/Women/Hoodies/51.png",
    "assets/images/products/Women/Hoodies/52.png",
  ];

  //Women Jens List
  static List womenJensList = [
    "assets/images/products/Women/Jens/1.png",
    "assets/images/products/Women/Jens/2.png",
    "assets/images/products/Women/Jens/3.png",
    "assets/images/products/Women/Jens/4.png",
    "assets/images/products/Women/Jens/5.png",
    "assets/images/products/Women/Jens/6.png",
    "assets/images/products/Women/Jens/7.png",
    "assets/images/products/Women/Jens/8.png",
    "assets/images/products/Women/Jens/9.png",
    "assets/images/products/Women/Jens/10.png",
    "assets/images/products/Women/Jens/11.png",
    "assets/images/products/Women/Jens/12.png",
    "assets/images/products/Women/Jens/13.png",
    "assets/images/products/Women/Jens/14.png",
    "assets/images/products/Women/Jens/15.png",
    "assets/images/products/Women/Jens/16.png",
    "assets/images/products/Women/Jens/17.png",
    "assets/images/products/Women/Jens/18.png",
    "assets/images/products/Women/Jens/19.png",
    "assets/images/products/Women/Jens/20.png",
    "assets/images/products/Women/Jens/21.png",
    "assets/images/products/Women/Jens/22.png",
    "assets/images/products/Women/Jens/23.png",
    "assets/images/products/Women/Jens/24.png",
    "assets/images/products/Women/Jens/25.png",
    "assets/images/products/Women/Jens/26.png",
    "assets/images/products/Women/Jens/27.png",
    "assets/images/products/Women/Jens/28.png",
    "assets/images/products/Women/Jens/29.png",
    "assets/images/products/Women/Jens/30.png",
  ];

  //Women Polo Shirtts List
  static List womenPoloShirtsList = [
    "assets/images/products/Women/Polo Shirts/1.png",
    "assets/images/products/Women/Polo Shirts/2.png",
    "assets/images/products/Women/Polo Shirts/3.png",
    "assets/images/products/Women/Polo Shirts/4.png",
    "assets/images/products/Women/Polo Shirts/5.png",
    "assets/images/products/Women/Polo Shirts/6.png",
    "assets/images/products/Women/Polo Shirts/7.png",
    "assets/images/products/Women/Polo Shirts/8.png",
    "assets/images/products/Women/Polo Shirts/9.png",
    "assets/images/products/Women/Polo Shirts/10.png",
    "assets/images/products/Women/Polo Shirts/11.png",
    "assets/images/products/Women/Polo Shirts/12.png",
    "assets/images/products/Women/Polo Shirts/13.png",
    "assets/images/products/Women/Polo Shirts/14.png",
    "assets/images/products/Women/Polo Shirts/15.png",
    "assets/images/products/Women/Polo Shirts/16.png",
    "assets/images/products/Women/Polo Shirts/17.png",
    "assets/images/products/Women/Polo Shirts/18.png",
    "assets/images/products/Women/Polo Shirts/19.png",
    "assets/images/products/Women/Polo Shirts/20.png",
    "assets/images/products/Women/Polo Shirts/21.png",
    "assets/images/products/Women/Polo Shirts/22.png",
    "assets/images/products/Women/Polo Shirts/23.png",
    "assets/images/products/Women/Polo Shirts/24.png",
    "assets/images/products/Women/Polo Shirts/25.png",
    "assets/images/products/Women/Polo Shirts/26.png",
    "assets/images/products/Women/Polo Shirts/27.png",
    "assets/images/products/Women/Polo Shirts/28.png",
    "assets/images/products/Women/Polo Shirts/29.png",
    "assets/images/products/Women/Polo Shirts/30.png",
    "assets/images/products/Women/Polo Shirts/31.png",
    "assets/images/products/Women/Polo Shirts/32.png",
    "assets/images/products/Women/Polo Shirts/33.png",
    "assets/images/products/Women/Polo Shirts/34.png",
    "assets/images/products/Women/Polo Shirts/35.png",
    "assets/images/products/Women/Polo Shirts/36.png",
    "assets/images/products/Women/Polo Shirts/37.png",
    "assets/images/products/Women/Polo Shirts/38.png",
    "assets/images/products/Women/Polo Shirts/39.png",
    "assets/images/products/Women/Polo Shirts/40.png",
    "assets/images/products/Women/Polo Shirts/41.png",
    "assets/images/products/Women/Polo Shirts/42.png",
    "assets/images/products/Women/Polo Shirts/43.png",
    "assets/images/products/Women/Polo Shirts/44.png",
    "assets/images/products/Women/Polo Shirts/45.png",
    "assets/images/products/Women/Polo Shirts/46.png",
    "assets/images/products/Women/Polo Shirts/47.png",
    "assets/images/products/Women/Polo Shirts/48.png",
    "assets/images/products/Women/Polo Shirts/49.png",
    "assets/images/products/Women/Polo Shirts/50.png",
    "assets/images/products/Women/Polo Shirts/51.png",
    "assets/images/products/Women/Polo Shirts/52.png",
  ];

  //Women shirt_and_pant List
  static List womenShirtsAndPantsList = [
    "assets/images/products/Women/shirt_and_pant/1.png",
    "assets/images/products/Women/shirt_and_pant/2.png",
    "assets/images/products/Women/shirt_and_pant/3.png",
    "assets/images/products/Women/shirt_and_pant/4.png",
    "assets/images/products/Women/shirt_and_pant/5.png",
    "assets/images/products/Women/shirt_and_pant/6.png",
    "assets/images/products/Women/shirt_and_pant/7.png",
    "assets/images/products/Women/shirt_and_pant/8.png",
    "assets/images/products/Women/shirt_and_pant/9.png",
    "assets/images/products/Women/shirt_and_pant/10.png",
    "assets/images/products/Women/shirt_and_pant/11.png",
    "assets/images/products/Women/shirt_and_pant/12.png",
    "assets/images/products/Women/shirt_and_pant/13.png",
    "assets/images/products/Women/shirt_and_pant/14.png",
    "assets/images/products/Women/shirt_and_pant/15.png",
    "assets/images/products/Women/shirt_and_pant/16.png",
    "assets/images/products/Women/shirt_and_pant/17.png",
    "assets/images/products/Women/shirt_and_pant/18.png",
    "assets/images/products/Women/shirt_and_pant/19.png",
    "assets/images/products/Women/shirt_and_pant/20.png",
    "assets/images/products/Women/shirt_and_pant/21.png",
    "assets/images/products/Women/shirt_and_pant/22.png",
    "assets/images/products/Women/shirt_and_pant/23.png",
    "assets/images/products/Women/shirt_and_pant/24.png",
    "assets/images/products/Women/shirt_and_pant/25.png",
    "assets/images/products/Women/shirt_and_pant/26.png",
    "assets/images/products/Women/shirt_and_pant/27.png",
    "assets/images/products/Women/shirt_and_pant/28.png",
    "assets/images/products/Women/shirt_and_pant/29.png",
    "assets/images/products/Women/shirt_and_pant/30.png",
    "assets/images/products/Women/shirt_and_pant/31.png",
    "assets/images/products/Women/shirt_and_pant/32.png",
    "assets/images/products/Women/shirt_and_pant/33.png",
    "assets/images/products/Women/shirt_and_pant/34.png",
    "assets/images/products/Women/shirt_and_pant/35.png",
    "assets/images/products/Women/shirt_and_pant/36.png",
    "assets/images/products/Women/shirt_and_pant/37.png",
    "assets/images/products/Women/shirt_and_pant/38.png",
    "assets/images/products/Women/shirt_and_pant/39.png",
    "assets/images/products/Women/shirt_and_pant/40.png",
    "assets/images/products/Women/shirt_and_pant/41.png",
    "assets/images/products/Women/shirt_and_pant/42.png",
    "assets/images/products/Women/shirt_and_pant/43.png",
    "assets/images/products/Women/shirt_and_pant/44.png",
    "assets/images/products/Women/shirt_and_pant/45.png",
    "assets/images/products/Women/shirt_and_pant/46.png",
    "assets/images/products/Women/shirt_and_pant/47.png",
    "assets/images/products/Women/shirt_and_pant/48.png",
    "assets/images/products/Women/shirt_and_pant/49.png",
    "assets/images/products/Women/shirt_and_pant/50.png",
    "assets/images/products/Women/shirt_and_pant/51.png",
    "assets/images/products/Women/shirt_and_pant/52.png",
    "assets/images/products/Women/shirt_and_pant/53.png",
    "assets/images/products/Women/shirt_and_pant/54.png",
    "assets/images/products/Women/shirt_and_pant/55.png",
    "assets/images/products/Women/shirt_and_pant/56.png",
    "assets/images/products/Women/shirt_and_pant/57.png",
    "assets/images/products/Women/shirt_and_pant/58.png",
    "assets/images/products/Women/shirt_and_pant/59.png",
    "assets/images/products/Women/shirt_and_pant/60.png",
    "assets/images/products/Women/shirt_and_pant/61.png",
    "assets/images/products/Women/shirt_and_pant/62.png",
    "assets/images/products/Women/shirt_and_pant/63.png",
    "assets/images/products/Women/shirt_and_pant/64.png",
    "assets/images/products/Women/shirt_and_pant/65.png",
    "assets/images/products/Women/shirt_and_pant/66.png",
    "assets/images/products/Women/shirt_and_pant/67.png",
    "assets/images/products/Women/shirt_and_pant/68.png",
    "assets/images/products/Women/shirt_and_pant/69.png",
    "assets/images/products/Women/shirt_and_pant/70.png",
    "assets/images/products/Women/shirt_and_pant/71.png",
    "assets/images/products/Women/shirt_and_pant/72.png",
    "assets/images/products/Women/shirt_and_pant/73.png",
    "assets/images/products/Women/shirt_and_pant/74.png",
    "assets/images/products/Women/shirt_and_pant/75.png",
    "assets/images/products/Women/shirt_and_pant/76.png",
    "assets/images/products/Women/shirt_and_pant/77.png",
    "assets/images/products/Women/shirt_and_pant/78.png",
    "assets/images/products/Women/shirt_and_pant/79.png",
  ];

  //Women short_and_cargo List
  static List womenShortsAndCargoList = [
    "assets/images/products/Women/short_and_cargo/1.png",
    "assets/images/products/Women/short_and_cargo/2.png",
    "assets/images/products/Women/short_and_cargo/3.png",
    "assets/images/products/Women/short_and_cargo/4.png",
    "assets/images/products/Women/short_and_cargo/5.png",
    "assets/images/products/Women/short_and_cargo/6.png",
    "assets/images/products/Women/short_and_cargo/7.png",
    "assets/images/products/Women/short_and_cargo/8.png",
    "assets/images/products/Women/short_and_cargo/9.png",
    "assets/images/products/Women/short_and_cargo/10.png",
    "assets/images/products/Women/short_and_cargo/11.png",
    "assets/images/products/Women/short_and_cargo/12.png",
    "assets/images/products/Women/short_and_cargo/13.png",
    "assets/images/products/Women/short_and_cargo/14.png",
    "assets/images/products/Women/short_and_cargo/15.png",
    "assets/images/products/Women/short_and_cargo/16.png",
    "assets/images/products/Women/short_and_cargo/17.png",
    "assets/images/products/Women/short_and_cargo/18.png",
    "assets/images/products/Women/short_and_cargo/19.png",
    "assets/images/products/Women/short_and_cargo/20.png",
    "assets/images/products/Women/short_and_cargo/21.png",
    "assets/images/products/Women/short_and_cargo/22.png",
    "assets/images/products/Women/short_and_cargo/23.png",
    "assets/images/products/Women/short_and_cargo/24.png",
    "assets/images/products/Women/short_and_cargo/25.png",
    "assets/images/products/Women/short_and_cargo/26.png",
    "assets/images/products/Women/short_and_cargo/27.png",
    "assets/images/products/Women/short_and_cargo/28.png",
    "assets/images/products/Women/short_and_cargo/29.png",
    "assets/images/products/Women/short_and_cargo/30.png",
    "assets/images/products/Women/short_and_cargo/31.png",
    "assets/images/products/Women/short_and_cargo/32.png",
    "assets/images/products/Women/short_and_cargo/33.png",
    "assets/images/products/Women/short_and_cargo/34.png",
    "assets/images/products/Women/short_and_cargo/35.png",
    "assets/images/products/Women/short_and_cargo/36.png",
    "assets/images/products/Women/short_and_cargo/37.png",
    "assets/images/products/Women/short_and_cargo/38.png",
    "assets/images/products/Women/short_and_cargo/39.png",
    "assets/images/products/Women/short_and_cargo/40.png",
    "assets/images/products/Women/short_and_cargo/41.png",
    "assets/images/products/Women/short_and_cargo/42.png",
    "assets/images/products/Women/short_and_cargo/43.png",
    "assets/images/products/Women/short_and_cargo/44.png",
    "assets/images/products/Women/short_and_cargo/45.png",
    "assets/images/products/Women/short_and_cargo/46.png",
    "assets/images/products/Women/short_and_cargo/47.png",
    "assets/images/products/Women/short_and_cargo/48.png",
    "assets/images/products/Women/short_and_cargo/49.png",
  ];

  //Women Sweaters List
  static List womenSweatersList = [
    "assets/images/products/Women/Sweaters/1.jpg",
    "assets/images/products/Women/Sweaters/2.png",
    "assets/images/products/Women/Sweaters/3.png",
    "assets/images/products/Women/Sweaters/4.jpg",
    "assets/images/products/Women/Sweaters/5.jpg",
    "assets/images/products/Women/Sweaters/6.jpg",
    "assets/images/products/Women/Sweaters/7.jpg",
    "assets/images/products/Women/Sweaters/8.jpg",
    "assets/images/products/Women/Sweaters/9.jpg",
    "assets/images/products/Women/Sweaters/10.jpg",
    "assets/images/products/Women/Sweaters/11.jpg",
    "assets/images/products/Women/Sweaters/12.jpg",
    "assets/images/products/Women/Sweaters/13.jpg",
    "assets/images/products/Women/Sweaters/14.jpg",
    "assets/images/products/Women/Sweaters/15.jpg",
    "assets/images/products/Women/Sweaters/16.jpg",
    "assets/images/products/Women/Sweaters/17.png",
    "assets/images/products/Women/Sweaters/18.png",
    "assets/images/products/Women/Sweaters/19.png",
    "assets/images/products/Women/Sweaters/20.png",
    "assets/images/products/Women/Sweaters/21.png",
    "assets/images/products/Women/Sweaters/22.png",
    "assets/images/products/Women/Sweaters/23.png",
    "assets/images/products/Women/Sweaters/24.png",
    "assets/images/products/Women/Sweaters/25.png",
    "assets/images/products/Women/Sweaters/26.png",
    "assets/images/products/Women/Sweaters/27.png",
    "assets/images/products/Women/Sweaters/28.png",
    "assets/images/products/Women/Sweaters/29.png",
    "assets/images/products/Women/Sweaters/30.png",
    "assets/images/products/Women/Sweaters/31.png",
    "assets/images/products/Women/Sweaters/32.jpg",
    "assets/images/products/Women/Sweaters/33.png",
    "assets/images/products/Women/Sweaters/34.png",
    "assets/images/products/Women/Sweaters/35.png",
    "assets/images/products/Women/Sweaters/36.png",
    "assets/images/products/Women/Sweaters/37.png",
    "assets/images/products/Women/Sweaters/38.jpg",
    "assets/images/products/Women/Sweaters/39.jpg",
    "assets/images/products/Women/Sweaters/40.jpg",
    "assets/images/products/Women/Sweaters/41.jpg",
    "assets/images/products/Women/Sweaters/42.jpg",
    "assets/images/products/Women/Sweaters/43.jpg",
    "assets/images/products/Women/Sweaters/44.jpg",
    "assets/images/products/Women/Sweaters/45.jpg",
    "assets/images/products/Women/Sweaters/46.jpg",
    "assets/images/products/Women/Sweaters/47.jpg",
    "assets/images/products/Women/Sweaters/48.jpg",
    "assets/images/products/Women/Sweaters/49.jpg",
    "assets/images/products/Women/Sweaters/50.jpg",
    "assets/images/products/Women/Sweaters/51.jpg",
    "assets/images/products/Women/Sweaters/52.jpg",
    "assets/images/products/Women/Sweaters/53.jpg",
    "assets/images/products/Women/Sweaters/54.jpg",
    "assets/images/products/Women/Sweaters/55.jpg",
    "assets/images/products/Women/Sweaters/56.jpg",
    "assets/images/products/Women/Sweaters/57.jpg",
    "assets/images/products/Women/Sweaters/58.jpg",
    "assets/images/products/Women/Sweaters/59.jpg",
    "assets/images/products/Women/Sweaters/60.jpg",
    "assets/images/products/Women/Sweaters/61.jpg",
    "assets/images/products/Women/Sweaters/62.jpg",
    "assets/images/products/Women/Sweaters/63.jpg",
    "assets/images/products/Women/Sweaters/64.jpg",
    "assets/images/products/Women/Sweaters/65.jpg",
    "assets/images/products/Women/Sweaters/66.jpg",
    "assets/images/products/Women/Sweaters/67.jpg",
    "assets/images/products/Women/Sweaters/68.jpg",
    "assets/images/products/Women/Sweaters/69.jpg",
    "assets/images/products/Women/Sweaters/70.jpg",
    "assets/images/products/Women/Sweaters/71.jpg",
    "assets/images/products/Women/Sweaters/72.jpg",
    "assets/images/products/Women/Sweaters/73.jpg",
    "assets/images/products/Women/Sweaters/74.jpg",
    "assets/images/products/Women/Sweaters/75.jpg",
    "assets/images/products/Women/Sweaters/76.jpg",
    "assets/images/products/Women/Sweaters/77.jpg",
    "assets/images/products/Women/Sweaters/78.jpg",
    "assets/images/products/Women/Sweaters/79.jpg",
    "assets/images/products/Women/Sweaters/80.jpg",
    "assets/images/products/Women/Sweaters/81.jpg",
    "assets/images/products/Women/Sweaters/82.jpg",
    "assets/images/products/Women/Sweaters/83.jpg",
    "assets/images/products/Women/Sweaters/84.jpg",
    "assets/images/products/Women/Sweaters/85.jpg",
    "assets/images/products/Women/Sweaters/86.jpg",
    "assets/images/products/Women/Sweaters/87.jpg",
    "assets/images/products/Women/Sweaters/88.jpg",
    "assets/images/products/Women/Sweaters/90.jpg",
    "assets/images/products/Women/Sweaters/91.jpg",
    "assets/images/products/Women/Sweaters/92.png",
    "assets/images/products/Women/Sweaters/93.jpg",
    "assets/images/products/Women/Sweaters/94.jpg",
    "assets/images/products/Women/Sweaters/95.jpg",
    "assets/images/products/Women/Sweaters/96.jpg",
    "assets/images/products/Women/Sweaters/97.jpg",
    "assets/images/products/Women/Sweaters/98.jpg",
    "assets/images/products/Women/Sweaters/99.jpg",
    "assets/images/products/Women/Sweaters/100.jpg",
    "assets/images/products/Women/Sweaters/101.jpg",
    "assets/images/products/Women/Sweaters/102.jpg",
    "assets/images/products/Women/Sweaters/103.jpg",
    "assets/images/products/Women/Sweaters/104.jpg",
    "assets/images/products/Women/Sweaters/105.jpg",
    "assets/images/products/Women/Sweaters/106.jpg",
    "assets/images/products/Women/Sweaters/107.jpg",
    "assets/images/products/Women/Sweaters/108.png",
    "assets/images/products/Women/Sweaters/109.jpg",
    "assets/images/products/Women/Sweaters/110.jpg",
    "assets/images/products/Women/Sweaters/111.jpg",
    "assets/images/products/Women/Sweaters/112.jpg",
    "assets/images/products/Women/Sweaters/113.jpg",
  ];

  //Womens T-Shirts List
  static List womensTShirtsList = [
    "assets/images/products/Women/T-Shirts/1.png",
    "assets/images/products/Women/T-Shirts/2.png",
    "assets/images/products/Women/T-Shirts/3.png",
    "assets/images/products/Women/T-Shirts/4.png",
    "assets/images/products/Women/T-Shirts/5.png",
    "assets/images/products/Women/T-Shirts/6.png",
    "assets/images/products/Women/T-Shirts/7.png",
    "assets/images/products/Women/T-Shirts/8.png",
    "assets/images/products/Women/T-Shirts/9.png",
    "assets/images/products/Women/T-Shirts/10.png",
    "assets/images/products/Women/T-Shirts/11.png",
    "assets/images/products/Women/T-Shirts/12.png",
    "assets/images/products/Women/T-Shirts/13.png",
    "assets/images/products/Women/T-Shirts/14.png",
    "assets/images/products/Women/T-Shirts/15.png",
    "assets/images/products/Women/T-Shirts/16.png",
    "assets/images/products/Women/T-Shirts/17.png",
    "assets/images/products/Women/T-Shirts/18.png",
    "assets/images/products/Women/T-Shirts/19.png",
    "assets/images/products/Women/T-Shirts/20.png",
    "assets/images/products/Women/T-Shirts/21.png",
    "assets/images/products/Women/T-Shirts/22.png",
    "assets/images/products/Women/T-Shirts/23.png",
    "assets/images/products/Women/T-Shirts/24.png",
    "assets/images/products/Women/T-Shirts/25.png",
    "assets/images/products/Women/T-Shirts/26.png",
    "assets/images/products/Women/T-Shirts/27.png",
    "assets/images/products/Women/T-Shirts/28.png",
    "assets/images/products/Women/T-Shirts/29.png",
    "assets/images/products/Women/T-Shirts/30.png",
    "assets/images/products/Women/T-Shirts/31.png",
    "assets/images/products/Women/T-Shirts/32.png",
    "assets/images/products/Women/T-Shirts/33.png",
    "assets/images/products/Women/T-Shirts/34.png",
    "assets/images/products/Women/T-Shirts/35.png",
    "assets/images/products/Women/T-Shirts/36.png",
    "assets/images/products/Women/T-Shirts/37.png",
    "assets/images/products/Women/T-Shirts/38.png",
    "assets/images/products/Women/T-Shirts/39.png",
    "assets/images/products/Women/T-Shirts/40.png",
    "assets/images/products/Women/T-Shirts/41.png",
    "assets/images/products/Women/T-Shirts/42.png",
    "assets/images/products/Women/T-Shirts/43.png",
    "assets/images/products/Women/T-Shirts/44.png",
    "assets/images/products/Women/T-Shirts/45.png",
    "assets/images/products/Women/T-Shirts/46.png",
    "assets/images/products/Women/T-Shirts/47.png",
    "assets/images/products/Women/T-Shirts/48.png",
    "assets/images/products/Women/T-Shirts/49.png",
    "assets/images/products/Women/T-Shirts/50.png",
  ];



  //Quality Page List
  static List qualityPointsList = [
    QualityAssurancePageText.QualityPoint1,
    QualityAssurancePageText.QualityPoint2,
    QualityAssurancePageText.QualityPoint3,
    QualityAssurancePageText.QualityPoint4,
    QualityAssurancePageText.QualityPoint5,
    QualityAssurancePageText.QualityPoint6,
    QualityAssurancePageText.QualityPoint7,
    QualityAssurancePageText.QualityPoint8,
  ];

  //Our Clients Page List
  static List ourClientsPageList = [
    AllImages.clientsLogo1,
    AllImages.clientsLogo2,
    AllImages.clientsLogo3,
    AllImages.clientsLogo4,
    // AllImages.clientsLogo5,
  ];
}
